apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: employeemanagement
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS employees (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      position VARCHAR(255),
      email VARCHAR(255),
      salary DECIMAL(10, 2)
    );