apiVersion: v1
kind: Secret
metadata:
    name: employee-secret
    namespace: employeemanagement
type: Opaque
stringData:
  DB_HOST: "mysql"
  DB_NAME: "employee_db"
  DB_USER: "root"
  DB_PASSWORD: "Rohit@123"
